### ISSUE TITLE
sys-clk manager 2.0.0-rc crashes at launch

### ISSUE THREAD

**Issue by christopher317** [retronx-team/sys-clk#69]
using system version 17, atmosphere v1.6.0pre, and sysclk v2.0pre

other sys extensions being used are:
open joystick display NX 
sysdvr

note:
when opening it in applet mode the payload crashes requiring a restart
but when opening it in app mode the software crashes and the system keeps running normally

**Comment by christopher317** [comment]
crash report:
[01697323733_010000000000100d.log](https://github.com/retronx-team/sys-clk/files/12908143/01697323733_010000000000100d.log)

**Comment by p-sam** [comment]
hmm the stack trace points to a fs error, could you try to copy the files again ? (faulty sdcard maybe?)

**Comment by christopher317** [comment]
> hmm the stack trace points to a fs error, could you try to copy the files again ? (faulty sdcard maybe?)

odd, i never had issues before updating the firmware to 17.0.0
il try that and see what happens

**Comment by christopher317** [comment]
same error, im going to try reinstalling atmosphere, im not sure if it was updated correctly.

**Comment by christopher317** [comment]
nope, still crashing.

**Comment by p-sam** [comment]
msg me on Discord, I'll help you fix the problem

**Comment by Semsemboy** [comment]
Having the same issue. Could you please post your solution here?

**Comment by p-sam** [comment]
I had no secret solution in mind, and did not get a response back. While we're not sure you're having the exact same problem, you can try:
- avoid copying the files directly, especially if on a mac (eg. via FTP)
- running archive bit fix in hekate

On this exact instance the crash happens at libnx cwd init, which is even before the actual manager code, which leeds me to believe it could be filesystem corruption

**Comment by christopher317** [comment]
> msg me on Discord, I'll help you fix the problem
finally found a invite link to the RetroNX discord, i sent a message under the username "christophertnt"

**Comment by christopher317** [comment]
best solution for now is to just use the overlay instead of the app. ( ty p-sam )

note:
this confused me, to get tesla menu to work, both the menu and overloader are needed.

**Comment by p-sam** [comment]
Well my bad, the problem must've been from the last minute recompilation with latest dkp packages (=> the gcc update), i've updated the manager in the zip attached to the prerelease. I'll leave this issue open for visibility until testing phase is over and it's released

**Comment by FaserF** [comment]
Just tried it with the latest rc2 2.0 version on AMS 1.6.1 and Firmware 16.1.0
For me it is unfortunatly still crashing.

**Comment by p-sam** [comment]
Can you include the report from the crash?

**Comment by FaserF** [comment]
Haven't tried the overlay yet. To be honest this module always was a set and forget module, wanted to do the same for some new Games and then let it be. 
But yeah if there is no fix I will give it a go

**Comment by ToxiClay** [comment]
If it's helpful, I downloaded the RC and the overlay is working fine on the latest HOS and pre-release AMS; it seems to pick things up and be functioning as expected. Manager NRO is working as well.

![2023102416113200-57B4628D2267231D57E0FC1078C0596D](https://github.com/retronx-team/sys-clk/assets/13796683/af463475-6e1c-4e36-be13-6e31be5fdc8c)

**Comment by FaserF** [comment]
Issue is now resolved with the latest AMS 1.6.2
Now everything works again without overlays.

**Comment by TheDBPI** [comment]
Unfortunately i have the same issue. i have AMS 1.6.2, hekate 6.0.7, at 17.0.0
The sys-clk overlay works but the .nro file doesn't.

**Comment by p-sam** [comment]
Closing this issue to avoid duplicating messages back and forth with this one: https://github.com/retronx-team/sys-clk/issues/72 

Please check if it works with the latest prerelease (it was updated today).

**Comment by XarceChronus** [comment]
Hey uh I'm still having this issue and I'm using the latest version of atmosphere...
